### ISSUE TITLE
180 deg longitude crossing

### ISSUE THREAD

**Issue by jaffadog** [mad-gooze/Leaflet.Arc#1]
arcs that cross 180 degrees longitude stop drawing at 180 degrees. leaflet defaults to a "wrapped" longitude model, where longitude>180 and longitude<-180 are permitted. when an arc is drawn between say [0,170] and [0,190], the arc will stop drawing half way through.

![screenshot - 2016-02-28 00 08 51](https://cloud.githubusercontent.com/assets/5514342/13377603/b04d2356-ddaf-11e5-88fa-ee7bff0c42b9.png)

**Comment by mad-gooze** [comment]
Thanks, fixed via 654d311b82bae7036814e473dc63cb22703b455f!
