### ISSUE TITLE
Polyline will not cross 180° (shortest path)

### ISSUE THREAD

**Issue by quantegy** [mad-gooze/Leaflet.Arc#2]
![Logbook Map](http://i.imgur.com/I8EIZ49.png)

Coordinates are [33.6442641, -117.8554282], [12.423, 123.514]

Is there something in arc.js needed to set to prevent this?

**Comment by mad-gooze** [comment]
Looks like this cannot be changed in arc.js settings, but you can subsctract 180 from your coordinates:

``` javascript
L.Polyline.Arc([33.6442641, -117.8554282], [12.423, 123.514-180]).addTo(map);
```

See [jsbin](http://jsbin.com/nuyowamico/edit?html,js,output).

**Comment by quantegy** [comment]
It's an issue with arc.js

**Comment by conease** [comment]
Coordinates [33.6442641, -117.8554282], [12.423, 123.514] are from Los Angeles, USA to Philippines. But when I subsctract 180 to the longitude of Philippines(12.423, 123.514), it moves to North Atlantic Ocean near Barbados. It does't resolve the issue.
