### ISSUE TITLE
How Animate Leaflet.Arc?

### ISSUE THREAD

**Issue by epozsh** [mad-gooze/Leaflet.Arc#4]
Is there any way to animate leaflet arc?

**Comment by mad-gooze** [comment]
Leaflet.Arc creates a usual Leaflet Polyline, so it seems that you can use some common techniques for polyline animations. I am not quite into leaflet ecosystem for some time, but 
[this page](http://leafletjs.com/plugins.html#overlay-animations) links to a couple of plugins which you can start from:
https://github.com/IvanSanchez/Leaflet.Polyline.SnakeAnim
https://github.com/rubenspgcavalcante/leaflet-ant-path

Please tell me if you get some results.

**Comment by mad-gooze** [comment]
Please re-open issue if you have any questions.
