### ISSUE TITLE
arrow functions not supported in all browsers

### ISSUE THREAD

**Issue by FS-JuLi** [mad-gooze/Leaflet.Arc#5]
Your arrow functions like
`const _latLngToXY = latlng => ({
    x: latlng.lng,
    y: latlng.lat
});`
are not supported in IE11 and Opera Mini. Please change it to standard function for full cross browser support.

Source:
https://caniuse.com/#feat=arrow-functions

**Comment by mad-gooze** [comment]
Please use compiled version from 
https://github.com/mad-gooze/Leaflet.Arc/blob/master/bin/leaflet-arc.min.js
