### ISSUE TITLE
Cannot read property 'lng' of null

### ISSUE THREAD

**Issue by bradleygraber** [mad-gooze/Leaflet.Arc#6]
I get this error when I try to called L.Polyline.Arc from your plugin.  I am loading leaflet first, and then your plugin.

**Comment by bradleygraber** [comment]
const _latLngToXY = latlng => ({
    x: latlng.lng,
    y: latlng.lat
});

**Comment by bradleygraber** [comment]
Sorry, I was passing in an array of two locations, rather than passing in the two locations separately.  It works when I pass in the items properly.

**Comment by mad-gooze** [comment]
Nice that you worked it out!
