### ISSUE TITLE
Please add a license (MIT or BSD, if possible)

### ISSUE THREAD

**Issue by ndobb** [mad-gooze/Leaflet.Arc#7]
Hi, nice work! We'd like to use this in an app for academic medical centers but noticed there appears to be no license for the repo. Could you please add a license, preferably MIT or BSD?

**Comment by ndobb** [comment]
@mad-gooze Can you please take a look at this? Thank you.

**Comment by mad-gooze** [comment]
https://github.com/mad-gooze/Leaflet.Arc/blob/master/LICENSE.md
