### ISSUE TITLE
straight line in short distance

### ISSUE THREAD

**Issue by ccolonna** [mad-gooze/Leaflet.Arc#9]
Hello,

i'm trying to use the plugin to draw arcs on a map.
```
 var path = L.Polyline.Arc( 
[ 48.8611473, 2.33802768704666 ] , [ 41.3751984992, 2.12036451854 ], {
            vertices: 100,
        }).addTo(myMap)
```

With these coordinates it shows a line instead of an arc,

may be due to a problem with short distances?

I tried also the following demo example and it works well :
```
    L.Polyline.Arc([59.56667, 150.8], [67.5, 64.03333], {
      color: "red",
      vertices: 200
    }).addTo(map);
```

**Comment by mad-gooze** [comment]
Hi @Christian-Nja!

Leaflet.Arc creates greate circle arcs (see https://en.wikipedia.org/wiki/Great-circle_distance).

Coords that you pass have a very close longitude, and great circle arc for them looks almost like a straight line.
